nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.1.cjs

# Add this section to handle the React 19 / Pliny conflict
nmMode: hardlinks-local
# This tells yarn to ignore the strict peer dependency check during resolution
checksumBehavior: update